// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


export const supabase = createClient<Database>(
  import.meta.env.VITE_PUBLIC_SUPABASE_URL, 
  import.meta.env.VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});